### ISSUE TITLE
Easy Audio Sync won't transfer tags properly if extension is ".FLAC" instead of ".flac"

### ISSUE THREAD

**Issue by Tom4tot** [complexlogic/EasyAudioSync#6]
I have noticed some of my files didn't have proper tags after using your program. It took me quite a bit of time to understand it wasn't related to paths length or something else... but the way the file extension is written.

Of course, I shouldn't have any .FLAC files, and I will rename them, but I don't think it should affect how your program behaves.

I think the issue is easy enough to reproduce so I won't share files, but let me know if you can't reproduce it, I'll be happy to help!
![Screenshot  2670](https://github.com/complexlogic/EasyAudioSync/assets/32274750/3c20de15-a804-48ae-a289-fbfb0ba95027)

**Comment by complexlogic** [comment]
Thanks for the report. I intended for the program to handle file extensions case insensitively, but there were a couple bugs in the implementation.
