### ISSUE TITLE
Cannot install .deb on Linux Mint 21.2

### ISSUE THREAD

**Issue by Neinei0k** [complexlogic/EasyAudioSync#8]
There is no package qtbase5 in the default repository of Linux Mint 21.2, and EasyAudioSync requires libc6 version 2.36, while latest version in the repo is 2.35.

My workaround is to just extract executable file from the .deb archive. It seems to run fine. The only issue I saw is when renaming directories from the directory selection dialog box, there is some visual bug that your typed characters are imposed on top of the old name. But this is probably related to some incompatibility between required qtbase5 package and whatever I have instead.

**Comment by complexlogic** [comment]
The .deb package was built on Debian Bullseye. Due to some dependency differences, it may not work on other `apt`-based distros.

The best workaround is to build from source. See the instructions [here](https://github.com/complexlogic/EasyAudioSync/blob/master/docs/building.md).
